#pragma once

#define BOOTMAGIC_LITE_ROW          0
#define BOOTMAGIC_LITE_COLUMN       0
#define BOOTMAGIC_LITE_ROW_RIGHT    6
#define BOOTMAGIC_LITE_COLUMN_RIGHT 0

#define SPLIT_TRANSACTION_IDS_USER RPC_HPD3_CONFIG

/* Serial settings */
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SPLIT_HAND_PIN      GP29
#define SPLIT_WATCHDOG_ENABLE
#define SELECT_SOFT_SERIAL_SPEED 1

#define ENCODER_RESOLUTION 4
#define ENCODER_DEFAULT_POS 0x3

#define WS2812_DI_PIN GP25
#define RGBLIGHT_LED_COUNT 2
#define RGBLED_SPLIT { 1, 1 }
#define RGBLIGHT_SLEEP
#define RGBLIGHT_SPLIT
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 16
#define RGBLIGHT_LAYERS_RETAIN_VAL
#define RGBLIGHT_DEFAULT_VAL 50
#define RGBLIGHT_LIMIT_VAL 150
#define RGBLIGHT_DEFAULT_SAT 0

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP20
#define I2C1_SCL_PIN GP21

#define AZOTEQ_IQS5XX_TPS43
#define AZOTEQ_IQS5XX_ROTATION_270
#define AZOTEQ_IQS5XX_REPORT_RATE 10
#define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE true
#define AZOTEQ_IQS5XX_HOLD_TIME 200
#define AZOTEQ_IQS5XX_TAP_TIME 175
#define AZOTEQ_IQS5XX_TAP_DISTANCE 50
#define AZOTEQ_IQS5XX_ZOOM_ENABLE false

#define PMW3610_SCLK_PIN 10
#define PMW3610_SDIO_PIN 11
#define PMW3610_CS_PIN   9

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_TASK_THROTTLE_MS 10

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4
#define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0x03324400

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4

#define EH_POINTING_KEYCODES
