#ifndef DYNAMIC_KEYMAP_LAYER_COUNT
#    define DYNAMIC_KEYMAP_LAYER_COUNT 16
#endif

#ifndef DYNAMIC_KEYMAP_MACRO_COUNT
#    define DYNAMIC_KEYMAP_MACRO_COUNT 109
#endif

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET              // Activates the double-tap behavior
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U // Timeout window in ms in which the double tap can occur.
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED_MASK 0U  // Specify a optional status led which blinks when entering the bootloader

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS, UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_WINDOWS

#define DEBOUNCE 10
#define USB_SUSPEND_WAKEUP_DELAY 2000 // wait for USB hub to start

#define WEAR_LEVELING_BACKING_SIZE 16384 // increase EEPROM size

#define OLED_FONT_H "src/oled/eh_oled_font.c"
#define OLED_TIMEOUT 0
#define EH_TIMEOUT (10 * 60 * 1000) // 10 minutes

#define TAPPING_TOGGLE 5

#define MOUSE_EXTENDED_REPORT
#define WHEEL_EXTENDED_REPORT

#ifdef CONSOLE_ENABLE
#    undef NO_DEBUG
#endif

#define KB_SETTINGS
#define KB_SETTINGS_RUEN_SIZE 4
#define KB_SETTINGS_RUEN_OFFSET 0
#define KB_SETTINGS_RUEN_PROTOS 3

#define KB_SETTINGS_POINTING_SIZE 8
#define KB_SETTINGS_POINTING_OFFSET (KB_SETTINGS_RUEN_OFFSET + KB_SETTINGS_RUEN_SIZE)
#define KB_SETTINGS_POINTING_PROTOS 16

#define LAYER_LABEL_SIZE 16
#define KB_SETTINGS_LAYER_LABELS_SIZE (DYNAMIC_KEYMAP_LAYER_COUNT * LAYER_LABEL_SIZE)
#define KB_SETTINGS_LAYER_LABELS_OFFSET (KB_SETTINGS_POINTING_OFFSET + KB_SETTINGS_POINTING_SIZE)
#define KB_SETTINGS_LAYER_LABELS_PROTOS DYNAMIC_KEYMAP_LAYER_COUNT

#define EECONFIG_KB_DATA_SIZE (KB_SETTINGS_RUEN_SIZE + KB_SETTINGS_POINTING_SIZE + KB_SETTINGS_LAYER_LABELS_SIZE)
#define KB_SETTINGS_NPROTOS (KB_SETTINGS_RUEN_PROTOS + KB_SETTINGS_POINTING_PROTOS + KB_SETTINGS_LAYER_LABELS_PROTOS)
